# Variable File containing cluster volume config and storage group details
---
# Main Variable Inputs for Playbook
portgroup_name: Ansible_DEMO_PG
mv_name: Ansible_Cluster_MV
sg_name: Ansible_Cluster_SG
host1_name: Ansible_Cluster_Host1_IG
host2_name: Ansible_Cluster_Host2_IG
hostgroup_name: Ansible_Cluster_IG

# Ports to be Used

port_list:
  - director_id: FA-1D
    port_id: 8 
  - director_id: FA-2D
    port_id: 8

# Host Initiators

host1_initiators:
  - 10000000c98ffaee
  - 10000000c98ffaef

host2_initiators:
  - 10000000c98ffffe
  - 10000000c98ffafe

# Storage Definition
    
volume_list:
  - vol_name: UniDev1
    size: 1
    cap_unit: GB
  - vol_name: UniDev2
    size: 1
    cap_unit: GB
  - vol_name: UniDev3
    size: 1
    cap_unit: GB

