---
- name: Protecting a Storage Group with SRDF
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - connection.yml
    - credentials.yml

  vars:
    sg_name: "pm_rdf_ansible"

    input: &uni_connection_vars
      serial_no: "{{ serial_no }}"
      password: "{{ password }}"
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      user: "{{  user  }}"
      verifycert: "{{ verifycert }}"

  tasks:
    - name: Create and establish storagegroup SRDF/S pairing
      dellemc_powermax_srdf:
        <<: *uni_connection_vars
        remote_serial_no: "000197900111"      
        sg_name: "{{sg_name}}"      
        srdf_mode: 'Synchronous'      
        srdf_state: 'Establish'      
        state: 'present'
      register: jobdetails    

