---
# Provision a Test Dev Setup from Snapshot of production
- name: Provisioning a test environment from source SG for Powermax
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars_files/connection.yml
    - vars_files/credentials.yml
    - vars_files/host_storage_details.yml
  vars:
    src_sg_name: "{{ sg_name }}"
    test_sg_name: "{{ sg_name + '_LNKSG' }}"

    input: &uni_connection_vars
      serial_no: "{{ serial_no }}"
      password: "{{ password }}"
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      user: "{{  user  }}"
      verifycert: "{{ verifycert }}"

  tasks:
   - debug:
       var: test_sg_name 
  
   - name: Create a Snapshot for a Storage Group
     dellemc_powermax_snapshot:
        <<: *uni_connection_vars
        sg_name: "{{ src_sg_name }}"
        snapshot_name: "ansible_sg_snap"
        ttl: "1"
        ttl_unit: "days"
        state: "present"

   - name: Change Snapshot Link Status to Linked
     dellemc_powermax_snapshot:
       <<: *uni_connection_vars
       sg_name: "{{ src_sg_name }}"
       snapshot_name: "ansible_sg_snap"
       generation: 0
       target_sg_name: "{{ test_sg_name }}"
       link_status: "linked"
       state: "present"

