---
- name: Protecting a Storage Group with SRDF
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars_files/connection.yml
    - vars_files/credentials.yml

  vars:
    app_name: "{{ app_name }}"
    remote_serial: "{{ remote_serial }}"
    input: &uni_connection_vars
      serial_no: "{{ serial_no }}"
      password: "{{ password }}"
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      user: "{{  user  }}"
      verifycert: "{{ verifycert }}"

  tasks:
    - name: Create and establish storagegroup SRDF/S pairing
      dellemc_powermax_srdf:
        <<: *uni_connection_vars
        remote_serial_no: "{{ remote_array }}"
        sg_name: "{{ 'Ansible_'+ app_name +'_SG' }}"
        srdf_mode: "{{ srdf_mode }}"
        srdf_state: 'Establish'
        state: 'present'
        wait_for_completion: True
      register: jobdetails
